// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tlcxtclqmdrbkavvprkg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRsY3h0Y2xxbWRyYmthdnZwcmtnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc3OTkxMzcsImV4cCI6MjA2MzM3NTEzN30.AhmTsfCKpzDn2gBIOL-4TAw-uNxXplLZPzw7RkNsqsc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);